[Interface]
PrivateKey = sNEt1g+qlVf5kXsnQy/fGcCRY5Sh2W5wAUC+v8SWuV4=
Address = 10.0.0.3/32
DNS = 1.1.1.1

[Peer]
PublicKey = z8/sLw6B50OS0swhFqXxhqD8+FqpwnOJvl207oGT9xk=
AllowedIPs = 0.0.0.0/0
Endpoint = 191.0.98.191:51820
PersistentKeepalive = 25
